import { TestCase } from './types';

export const STANDARD_TEST_PRESETS: TestCase[] = [
  {
    id: 'test_kinematics_reachability',
    name: 'Kinematics & Articulation Joint Sweep',
    description: 'Sweeps all revolute and continuous joints through their full range to detect limit violations and kinematic singularities.',
    category: 'kinematics',
    environment: 'grid',
    durationSec: 5,
    commandType: 'joint_sweep',
    commandParams: {},
    assertions: [
      {
        id: 'a_joint_error',
        label: 'Max Joint Angle Tracking Error',
        metric: 'max_joint_error_rad',
        operator: '<=',
        targetValue: 0.02,
        unit: 'rad',
      },
      {
        id: 'a_singularity',
        label: 'Singularity Avoidance Index',
        metric: 'singularity_index',
        operator: '>=',
        targetValue: 0.85,
        unit: 'score',
      },
    ],
  },
  {
    id: 'test_velocity_braking',
    name: 'Max Velocity & Emergency Braking Response',
    description: 'Accelerates the robot to its maximum rated speed, triggers an emergency brake, and measures stopping distance and deceleration time.',
    category: 'velocity_braking',
    environment: 'grid',
    durationSec: 6,
    commandType: 'emergency_stop',
    commandParams: { targetVelocity: 1.5 },
    assertions: [
      {
        id: 'a_max_speed',
        label: 'Top Speed Reached',
        metric: 'top_speed_ms',
        operator: '>=',
        targetValue: 1.2,
        unit: 'm/s',
      },
      {
        id: 'a_stopping_dist',
        label: 'Emergency Braking Stopping Distance',
        metric: 'stopping_distance_m',
        operator: '<=',
        targetValue: 0.45,
        unit: 'm',
      },
      {
        id: 'a_decel_time',
        label: 'Braking Deceleration Time',
        metric: 'decel_time_s',
        operator: '<=',
        targetValue: 0.75,
        unit: 's',
      },
    ],
  },
  {
    id: 'test_collision_avoidance',
    name: 'Warehouse Obstacle Proximity & Collision Stop',
    description: 'Navigates toward a stationary obstacle pallet in a logistics warehouse setting to verify collision avoidance response.',
    category: 'collision_avoidance',
    environment: 'warehouse',
    durationSec: 8,
    commandType: 'velocity_step',
    commandParams: { targetVelocity: 1.0, obstacleDistanceM: 3.0 },
    assertions: [
      {
        id: 'a_min_clearance',
        label: 'Minimum Obstacle Clearance',
        metric: 'min_clearance_m',
        operator: '>=',
        targetValue: 0.35,
        unit: 'm',
      },
      {
        id: 'a_collision_events',
        label: 'PhysX Rigid Body Collision Events',
        metric: 'collision_count',
        operator: '==',
        targetValue: 0,
        unit: 'events',
      },
    ],
  },
  {
    id: 'test_incline_stability',
    name: '15° Incline Ramp & Tip-Over Stability',
    description: 'Drives the robot up a 15-degree incline ramp to evaluate pitch stability, center of mass safety, and wheel traction.',
    category: 'incline_stability',
    environment: 'incline_slope',
    durationSec: 7,
    commandType: 'incline_drive',
    commandParams: { slopeAngleDeg: 15.0 },
    assertions: [
      {
        id: 'a_pitch_stability',
        label: 'Maximum Pitch Deviation',
        metric: 'max_pitch_deg',
        operator: '<=',
        targetValue: 16.0,
        unit: 'deg',
      },
      {
        id: 'a_wheel_slip',
        label: 'Wheel Slippage Ratio',
        metric: 'wheel_slip_ratio',
        operator: '<=',
        targetValue: 0.12,
        unit: 'ratio',
      },
    ],
  },
  {
    id: 'test_payload_capacity',
    name: 'Rated Payload & Joint Torque Saturation',
    description: 'Applies full rated payload to the chassis and verifies that actuator torques remain within safe thermal margins.',
    category: 'payload_capacity',
    environment: 'laboratory',
    durationSec: 6,
    commandType: 'custom_script',
    commandParams: { payloadMassKg: 10.0 },
    assertions: [
      {
        id: 'a_peak_torque',
        label: 'Peak Actuator Torque Margin',
        metric: 'peak_torque_nm',
        operator: '<=',
        targetValue: 24.0,
        unit: 'Nm',
      },
      {
        id: 'a_motor_saturation',
        label: 'Motor Torque Saturation Occurrences',
        metric: 'saturation_events',
        operator: '==',
        targetValue: 0,
        unit: 'events',
      },
    ],
  },
];
