import JSZip from 'jszip';
import { buildUrdfXml, validateDesign } from './serialize';
import type { RobotDesign } from '../user-robot-designs';

function toPackageName(name: string): string {
  const cleaned = name.trim().toLowerCase().replace(/[^a-z0-9_]+/g, '_').replace(/^_+|_+$/g, '');
  if (!cleaned) return 'robot_description';
  return /^[a-z]/.test(cleaned) ? cleaned : `robot_${cleaned}`;
}

function packageXml(pkg: string): string {
  return `<?xml version="1.0"?>
<package format="3">
  <name>${pkg}</name>
  <version>0.0.1</version>
  <description>Robot description generated by UpFreq Robots.</description>
  <maintainer email="you@example.com">TODO</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
`;
}

function cmakeLists(pkg: string): string {
  return `cmake_minimum_required(VERSION 3.8)
project(${pkg})

find_package(ament_cmake REQUIRED)

install(DIRECTORY urdf meshes
  DESTINATION share/\${PROJECT_NAME}
)

ament_package()
`;
}

/**
 * Bundles the design into an actual, colcon-buildable ROS 2 package: a real
 * package.xml + CMakeLists.txt, the URDF with package://<name>/meshes/...
 * references (which only resolve because the referenced files are
 * physically included here), and the mesh files themselves fetched from
 * Blob storage and re-embedded. Unlike the plain "Download" (direct HTTPS
 * mesh URLs, browser-preview only), this is meant to be unzipped straight
 * into a ROS workspace's src/ and built.
 */
export async function downloadRosPackage(design: RobotDesign): Promise<void> {
  const errors = validateDesign(design);
  if (errors.length > 0) {
    throw new Error(`Cannot export: ${errors[0]}`);
  }

  const packageName = toPackageName(design.name);
  const meshFileById = new Map(design.meshFiles.map((f) => [f.id, f]));

  const filenameByLinkId = new Map<string, string>();
  const usedNames = new Set<string>();
  for (const link of design.links) {
    if (!link.meshFileId || !link.meshUrl) continue;
    const original = meshFileById.get(link.meshFileId)?.originalFilename || `${link.name}.stl`;
    let filename = original.replace(/[^a-zA-Z0-9._-]/g, '_');
    if (usedNames.has(filename)) {
      const ext = filename.includes('.') ? filename.split('.').pop() : 'stl';
      const base = filename.replace(/\.[^.]+$/, '');
      filename = `${base}_${link.id.slice(0, 6)}.${ext}`;
    }
    usedNames.add(filename);
    filenameByLinkId.set(link.id, filename);
  }

  const xml = buildUrdfXml(design, {
    meshUri: (link) => `package://${packageName}/meshes/${filenameByLinkId.get(link.id) ?? `${link.name}.stl`}`,
  });

  const zip = new JSZip();
  zip.file(`urdf/${packageName}.urdf`, xml);
  zip.file('package.xml', packageXml(packageName));
  zip.file('CMakeLists.txt', cmakeLists(packageName));

  const meshFolder = zip.folder('meshes');
  if (!meshFolder) throw new Error('Failed to create meshes/ folder in the zip archive.');

  await Promise.all(
    design.links
      .filter((l) => l.meshUrl && filenameByLinkId.has(l.id))
      .map(async (l) => {
        const res = await fetch(l.meshUrl!);
        if (!res.ok) throw new Error(`Failed to fetch mesh for link "${l.name}" (${res.status})`);
        const blob = await res.blob();
        meshFolder.file(filenameByLinkId.get(l.id)!, blob);
      })
  );

  const zipBlob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(zipBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${packageName}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
