export type CadPrimitive =
  | { type: 'box'; size: [number, number, number]; center?: boolean }
  | { type: 'cylinder'; radius: number; height: number; center?: boolean; segments?: number }
  | { type: 'sphere'; radius: number; segments?: number }
  | { type: 'cone'; radiusBottom: number; radiusTop: number; height: number; center?: boolean; segments?: number };

export interface CadTransform {
  translate?: [number, number, number];
  rotate?: [number, number, number];
  scale?: [number, number, number];
}

export type CadNode =
  | { kind: 'primitive'; primitive: CadPrimitive; transform?: CadTransform }
  | { kind: 'boolean'; op: 'union' | 'difference' | 'intersection'; children: CadNode[]; transform?: CadTransform };

function num(n: number): string {
  // OpenSCAD is fine with plain decimals; trims float noise from JSON round-trips.
  return Number.isInteger(n) ? String(n) : n.toFixed(6).replace(/0+$/, '').replace(/\.$/, '');
}

function primitiveToScad(p: CadPrimitive): string {
  switch (p.type) {
    case 'box':
      return `cube([${p.size.map(num).join(', ')}], center=${p.center ?? true});`;
    case 'cylinder':
      return `cylinder(h=${num(p.height)}, r=${num(p.radius)}, center=${p.center ?? true}, $fn=${p.segments ?? 32});`;
    case 'sphere':
      return `sphere(r=${num(p.radius)}, $fn=${p.segments ?? 32});`;
    case 'cone':
      return `cylinder(h=${num(p.height)}, r1=${num(p.radiusBottom)}, r2=${num(p.radiusTop)}, center=${p.center ?? true}, $fn=${p.segments ?? 32});`;
  }
}

function wrapTransform(body: string, transform?: CadTransform): string {
  if (!transform) return body;
  let wrapped = body;
  if (transform.scale) wrapped = `scale([${transform.scale.map(num).join(', ')}]) ${wrapped}`;
  if (transform.rotate) wrapped = `rotate([${transform.rotate.map(num).join(', ')}]) ${wrapped}`;
  if (transform.translate) wrapped = `translate([${transform.translate.map(num).join(', ')}]) ${wrapped}`;
  return wrapped;
}

function nodeToScad(node: CadNode): string {
  if (node.kind === 'primitive') {
    return wrapTransform(primitiveToScad(node.primitive), node.transform);
  }

  const childrenScad = node.children.map(nodeToScad).join('\n  ');
  const body = `${node.op}() {\n  ${childrenScad}\n}`;
  return wrapTransform(body, node.transform);
}

/** Deterministically compiles a structured CAD tree into OpenSCAD source — pure text generation, no compiler invoked. */
export function generateScadSource(node: CadNode): string {
  return `// Generated by UpFreq upfreq.cad.generate_part — deterministic, not AI-authored.\n${nodeToScad(node)}\n`;
}
